spring:
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  rabbitmq:
    host: 192.168.137.199 #ls的电脑热点
    #host: 192.168.43.221 #ls的手机热点
    port: 5672
    username: admin
    password: 123456

## rabbitMQ properties ,the name as you like
ordermq:
  config:
    exchange: log.direct  # 交换器的名称
    queue:
      info:
        name: log.info  # 服务名称
        routing:
          key: log.info.routing.key # info路由键
