spring:
  rabbitmq:
    host: 10.66.66.17  # rabbitMQ server IP   127.0.0.1
#    host: localhost  # rabbitMQ server IP   127.0.0.1
    port: 5672       # rabbitMQ server port
    username: admin
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/coupon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: always
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379


server:
  port: 8091
  servlet:
    context-path: /consumer

## rabbitMQ properties ,the name as you like
mq:
  config:
    exchange: log.direct  # 交换器的名称
    queue:
      info:
        value: log.info  # 服务名称
        routing-key: log.info.routing.key # info路由键

