
server:
  port: 8086
  servlet:
    context-path: /coupon

spring:
  application:
    name: coupon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/coupon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: always
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as
  rabbitmq:
    host: 10.66.66.17 # rabbitMQ server IP
    port: 5672      # rabbitMQ server port
    username: admin
    password: 123456
#  redis:
#    database: 0
#    host: 10.66.66.17
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0



## rabbitMQ properties ,the name as you like
mq:
  config:
    exchange: log.direct  # 交换器的名称
    queue:
      info:
        value: log.info  # 服务名称
        routing-key: log.info.routing.key # info路由键


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:8761/eureka/  # 设置服务注册中心地址，指向另一个注册中心 ，结构是一定的：http://{hostname}:{port}/eureka/
##      defaultZone: http://cm01:8761/eureka/,http://cm02:8761/eureka/  # 设置服务注册中心地址，指向另一个注册中心 ，结构是一定的：http://{hostname}:{port}/eureka/

